apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: ml-pipeline
namespace: pipeline
resources:
- config-map.yaml
- deployment.yaml
- clusterrole-binding.yaml
- clusterrole.yaml
- service-account.yaml
- service.yaml
images:
- name: gcr.io/ml-pipeline/api-server
  newTag: 0.5.1
  newName: gcr.io/ml-pipeline/api-server
