apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: ml-pipeline
namespace: pipeline
resources:
- config-map.yaml
- deployment.yaml
- clusterrole-binding.yaml
- clusterrole.yaml
- service-account.yaml
- service.yaml
images:
- name: gcr.io/ml-pipeline/api-server
  # newTag: 0.3.0
  newTag: eb69a6b8ae2d82cd8574ed11f04af4607756061c
  # newName: gcr.io/ml-pipeline/api-server
  newName: gcr.io/ml-pipeline-test/api-server
configurations:
- params.yaml
vars:
- name: namespace
  objref:
    kind: ServiceAccount
    name: ml-pipeline
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
