apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-pipeline-ui-configmap
data:
   # Temporary workarounds:
   # 1. Using default-editor because default-viewer isn't bound to workload identity
   # 2. Disable istio sidecar injection to allow all traffic
   # TODO:
   # 1. Set up default-viewer with only read access with workload identity
   # 2. Enable istio sidecar injection and only allow ml-pipeline-ui for proxy
   viewer-pod-template.json:  |-
    {
    "metadata": {
      "annotations": { "sidecar.istio.io/inject": "false" }
    },
    "spec": {
        "serviceAccountName": "default-editor"
    }
    }
