apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-pipeline-ui-configmap
data:
   # Temporary workarounds:
   # 1. Using default-editor because default-viewer isn't bound to workload identity
   # 2. Disable istio sidecar because UI server needs to proxy user email for verification
   viewer-pod-template.json:  |-
    {
    "metadata": {	
      "annotations": { "sidecar.istio.io/inject": "false" }	
    },
    "spec": {
        "serviceAccountName": "default-editor"
    }
    }
