varReference:
- path: metadata/annotations/getambassador.io\/config
  kind: Service
- path: subjects/namespace
  kind: ClusterRoleBinding
- path: spec/template/spec/containers/env/value
  kind: Deployment
