apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../generic
- api-service
- pipelines-ui
- pipelines-profile-controller
- scheduled-workflow
patchesStrategicMerge:
- api-service/deployment-patch.yaml
- pipelines-ui/deployment-patch.yaml
- viewer-crd-deployment-patch.yaml
- scheduled-workflow/deployment-patch.yaml
