apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: profile-controller
spec:
  generateSelector: true
  resyncPeriodSeconds: 10
  parentResource:
    apiVersion: kubeflow.org/v1
    resource: profiles
  childResources:
  - apiVersion: v1
    resource: secrets
    updateStrategy:
      method: OnDelete
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: OnDelete
  hooks:
    sync:
      webhook:
        url: http://kubeflow-pipelines-profile-controller/sync
