apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
nameprefix: kubeflow-pipelines-
commonLabels:
  app: kubeflow-pipelines-profile-controller
resources:
- service.yaml
- deployment.yaml
- configmap.yaml
- composite-controller.yaml
