apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: profile-controller
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: profile-controller
        image: python:2.7
        command: ["python", "/hooks/sync.py"]
        env:
        - name: KFP_VERSION
          value: 1.0.0-rc.3
        - name: DISABLE_ISTIO_SIDECAR
          value: "true" # TODO: make visualization server work with sidecar
        volumeMounts:
        - name: hooks
          mountPath: /hooks
        ports:
        - containerPort: 80
      volumes:
      - name: hooks
        configMap:
          name: profile-controller
